#! /bin/sh -f
#\
mkdir -p logfiles
#\
exec tessent -shell -log logfiles/$0.log -replace -dofile "$0"

set PDK_ROOT ../../tech
set design_name croc_chip 
# Set the context to insert DFT into RTL-level design
set_context dft -rtl -design_id rtl1

# Set the location of the TSDB. Default is the current working directory.
set_tsdb_output_directory ../tsdb_outdir


# Read the cell library
read_cell_library ${PDK_ROOT}/tessent/ihp-sg13g2_stdcell.tcelllib
read_cell_library ${PDK_ROOT}/tessent/ihp-sg13g2_io.tcelllib

# Define location of memory library files
set_design_sources -format tcd_memory -Y ${PDK_ROOT}/tessent/memories -extension tcd_memory

# Read memory verilog model
read_verilog ${PDK_ROOT}/ihp-sg13g2/libs.ref/sg13g2_sram/t-verilog/*.v -exclude_from_file_dictionary -interface_only
# Read the verilog
read_verilog -format sv2009 -f croc.flist -verbose

set_current_design ${design_name}

# Set the design level before running check_design_rules
set_design_level chip

# Define set_dft_specification_requirements
set_dft_specification_requirements -boundary_scan on -memory_test on

# Specify the TAP pins using set_attribute_value
set_attribute_value tck_p -name function -value tck
set_attribute_value tdi_p -name function -value tdi
set_attribute_value tms_p -name function -value tms
set_attribute_value trst_p -name function -value trst
set_attribute_value tdo_p -name function -value tdo

# it is important to prevent the clk ports to be targeted by the boundary scan, specially if they are used in different contexts
set_boundary_scan_port_options clk_i -cell_options dont_touch
set_boundary_scan_port_options rst_ni -cell_options dont_touch
set_boundary_scan_port_options jtag_tck_i -cell_options dont_touch
set_boundary_scan_port_options jtag_trst_ni -cell_options dont_touch

# Specify the clocks feeding memories
add_clocks 0 clk_i -period 10ns


#add_clocks 1 ref_clk_i -period 5ns

check_design_rules

# Create and report a DFT Specification
set spec [create_dft_specification]
report_config_data $spec

# Set parameter to divide the boundary scan chain into smaller segments to be used during logic test
set_config_value $spec/BoundaryScan/max_segment_length_for_logictest 100

report_config_data $spec

# Add auxilary mux on the inputs and outputs used for EDT Channel pins
read_config_data -in ${spec}/BoundaryScan -from_string {
  AuxiliaryInputOutputPorts {
<ADD AUXILIARY INPUT PORTS>
<ADD AUXILIARY OUTPUT PORTS>
  }
}
report_config_data $spec

# Generate and insert the hardware
process_dft_specification

# Extract IJAG network and create ICL file for the design
extract_icl

# Provides new and original updated RTL into this new file to be elaborated and Synthesized later
# If not using logic test (EDT insertion in next step) this would be used for synthesis
#write_design_import_script  use_in_synthesis.tcl -replace

# Generate patterns to verify the inserted DFT logic
create_pattern_specification
process_patterns_specification

# Point to the libraries and run the simulation 
set_simulation_library_sources -v ${PDK_ROOT}/ihp-sg13g2/libs.ref/sg13g2_stdcell/verilog/sg13g2_stdcell.v -v ${PDK_ROOT}/ihp-sg13g2/libs.ref/sg13g2_io/verilog/sg13g2_io.v -v ${PDK_ROOT}/ihp-sg13g2/libs.ref/sg13g2_sram/t-verilog/*.v 
run_testbench_simulations

# If simulation fails, use this command to see which pattern failed
check_testbench_simulations

exit
