#! /bin/sh -f
#\
mkdir -p logfiles
#\
exec tessent -shell -log logfiles/$0.log -replace -dofile "$0"
##==========TESTPOINT, Xbounding, Wrapper and Scan Insertion  ===================================== 

set PDK_ROOT ../../../tech
# Open the previous TSDB directories if it is not in the current working directory
set_tsdb_output_directory ../tsdb_outdir

##Setting context to dft and  we are inserting DFT into gate-level design
set_context dft -test_points -scan -no_rtl -design_id gate3

##Read in the design # may use  -exclude_from_file_dictionary to exclude the netlist from tessent databse i
read_cell_library ${PDK_ROOT}/tessent/ihp-sg13g2_stdcell.tcelllib
read_cell_library ${PDK_ROOT}/tessent/ihp-sg13g2_io.tcelllib

# Read the synthesized netlist

##Read in the memory library model
#set_design_sources -format tcd_memory -Y ${PDK_ROOT}/tessent/memories -extension tcd_memory

##Read in memory verilog model
#read_verilog ${PDK_ROOT}/ihp-sg13g2/libs.ref/sg13g2_sram/verilog/RM_IHPSG13_1P_core_behavioral_bm_bist.v -exclude_from_file_dictionary -interface_only
#read_verilog ${PDK_ROOT}/ihp-sg13g2/libs.ref/sg13g2_sram/verilog/RM_IHPSG13_1P_256x64_c2_bm_bist.v -exclude_from_file_dictionary -interface_only


# Read the design files from the RTL insertion pass
# Use the -no_hdl switch to skip reading the netlist as the synthesized netlist has already been read
read_design NV_NVDLA_partition_o -design_id gate2 

set_current_design NV_NVDLA_partition_o
add_black_boxes -modules {\
                        RAMDP_256X4_GL_M2_E2 \
                        RAMDP_256X8_GL_M2_E2 \
                        RAMPDP_128X18_GL_M2_D2 \
                        RAMDP_8X66_GL_M1_E2 \
                        RAMDP_80X9_GL_M2_E2 \
                        RAMPDP_80X17_GL_M2_D2 \
                        RAMDP_60X22_GL_M1_E2 \
                        }

##Setting the design level as physical_block
set_design_level physical_block

set_static_dft_signal_value ltest_en 1
#set_static_dft_signal_value force_testmode_i_zero 1

report_static_dft_signal_settings

add_nonscan_instances \u_NV_NVDLA_pdp/u_rdma/u_eg/u_lat_fifo/ram/r_nv_ram_rwsp_8x65/testInst_ram_access_lockup/Q_reg
add_nonscan_instances \u_NV_NVDLA_cdp/u_dp/u_NV_NVDLA_CDP_DP_syncfifo/u_sumpd_sync_fifo/ram/r_nv_ram_rwsthp_60x21/testInst_ram_access_lockup/Q_reg
add_nonscan_instances \u_NV_NVDLA_cdp/u_rdma/u_eg/u_lat_fifo/ram/r_nv_ram_rwsp_8x65/testInst_ram_access_lockup/Q_reg
add_nonscan_instances \u_NV_NVDLA_cdp/u_dp/u_NV_NVDLA_CDP_DP_syncfifo/u_info_sync_fifo/ram/r_nv_ram_rwsthp_80x17/testInst_ram_access_lockup/Q_reg
add_nonscan_instances \u_NV_NVDLA_cdp/u_dp/u_NV_NVDLA_CDP_DP_syncfifo/u_data_sync_fifo/ram/r_nv_ram_rwsthp_80x9/testInst_ram_access_lockup/Q_reg

# check design rule
set_system_mode analysis

# report clocks and dft signals
report_clocks
report_dft_signals
report_scan_segments

## exclude reset from Xbounding else will get XB DRC. Will be handled by wrapper insertion. Automation in 19.2
#set_xbounding_options  -exclude  {direct_reset_ dla_reset_rstn}

#Exclude the edt_channel in and out ports from wrapper chain analysis. The ijtag_* edt_update ports are automatically excluded
set_wrapper_analysis_options -exclude_ports [ get_ports {*_edt_channels_*} ]
set_dedicated_wrapper_cell_options on -ports dla_reset_rstn
set_dedicated_wrapper_cell_options on -ports direct_reset_

#Performs wrapper cell analysis
analyze_wrapper_cells
report_wrapper_cells -Verbose  > wrapper_cell.rpt


set edt_instance [get_instances -of_icl_instances [get_icl_instances -filter tessent_instrument_type==mentor::edt]]
add_scan_mode int_mode -type internal -edt_instance $edt_instance
add_scan_mode ext_mode -type external -chain_count 12

# Analyze the scan chains and review the different scan modes and chains before stitching the chains
analyze_scan_chains

# Insert scan chains and writes the scan inserted design into tsdb_outdir directory
insert_test_logic

report_scan_chains
report_scan_cells > scan_cells.list

exit
